"""empty message

Revision ID: 70e5bb3c24c3
Revises: 86d61882aa6b
Create Date: 2019-11-26 21:08:12.898674

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '70e5bb3c24c3'
down_revision = '86d61882aa6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('_password', sa.String(length=100), nullable=False))
    op.drop_column('cms_user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('password', mysql.VARCHAR(collation='utf8_bin', length=100), nullable=False))
    op.drop_column('cms_user', '_password')
    # ### end Alembic commands ###
